export const DECREASE_TIME = "DECREASE_TIME";
export const INCREASE_TIME = "INCREASE_TIME";
export const TIMER_START = "TIMER_START";
export const TIMER_PAUSE = "TIMER_PAUSE";
export const TIMER_RESTART = "TIMER_RESTART";
